version: '3'
services:
  anvil:
    image: "nwndotnet/anvil:${ANVIL_VERSION}"
    env_file:
      - ${PWD-.}/config/nwserver.env
    volumes:
      - ${PWD-.}/NWN.Toolbox.Tests:/nwn/home/anvil/Plugins/NWN.Toolbox.Tests
      - ${PWD-.}/paket:/nwn/home/anvil/Paket
      - ${PWD-.}/results:/nwn/home/anvil/PluginData/NWN.Anvil.TestRunner
